name: Deploy Nginx

on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t my-nginx-app .
      - run: docker rm -f my-nginx-app || true
      - run: docker run -d -p 8080:80 --name my-nginx-app my-nginx-app
